version: '3.8'

services:
  # --- Banco de Dados PostgreSQL ---
  db:
    image: postgres:15-alpine
    container_name: presenca_db
    environment:
      POSTGRES_DB: sistema_presenca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Backend (Spring Boot) ---
  backend:
    build:
      context: ./presenca-system  # Pasta do backend
    container_name: presenca_backend
    # Não expomos a porta 8080 publicamente, só o Nginx a acede
    environment:
      # Aponta o backend para o contentor do banco 'db'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sistema_presenca
      #
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # URL para os emails de recuperação de senha (agora no Nginx)
      - APP_FRONTEND_URL=http://localhost:8080
      # Configuração do MailHog
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
    depends_on:
      - db
      - mailhog

  # --- Frontend (Angular + Nginx) ---
  frontend:
    build:
      context: ./sitema-controle-presenca # Pasta do frontend
    container_name: presenca_frontend
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend

  # --- MailHog (captura emails) ---
  mailhog:
    image: mailhog/mailhog
    container_name: presenca_mailhog
    ports:
      - "8025:8025" # UI web
      - "1025:1025" # SMTP

# Volume para persistir os dados do banco
volumes:
  postgres_data: